sudo: false
os:
  - linux

language: node_js
node_js:
  - 5
  - 6
  - 7

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: npm
  skip_cleanup: true
  email: lindarian12@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: router-async/hook-history
